# Generated by Django 5.1.6 on 2025-03-05 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'categories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'chats',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PicturesCollection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'picturesCollections',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('photoPath', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('picturesPath', models.CharField(max_length=255)),
                ('picturesCollection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='myapp.picturescollection')),
            ],
            options={
                'db_table': 'pictures',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('cost', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='myapp.category')),
                ('picturesCollection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='myapp.picturescollection')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='myapp.user')),
            ],
            options={
                'db_table': 'products',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=255)),
                ('sendingTime', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='myapp.chat')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='myapp.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='myapp.user')),
            ],
            options={
                'db_table': 'messages',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='chat',
            name='firstUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_as_first_user', to='myapp.user'),
        ),
        migrations.AddField(
            model_name='chat',
            name='secondUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_as_second_user', to='myapp.user'),
        ),
    ]
