# Generated by Django 5.2.6 on 2025-09-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('logText', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'logs',
                'managed': True,
            },
        ),
    ]
