# Generated by Django 5.1.6 on 2025-03-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photoPath',
            field=models.CharField(blank=True, default='/pictures/users/defayult.png', max_length=255, null=True),
        ),
    ]
